sudo: required
services:
  - docker

before_install: 
  - docker build -t panickerthomas/docker-react -f Dockerfile.dev .

script: 
  - docker run panickerthomas/docker-react npm run test -- --coverage